import os
print ("Private offices are being downloaded in the tool")
print("∞"*60)
os.system('pip install requests')
os.system('pip install secrets')
os.system('pip install sys')
os.system('pip install datetime')
os.system('pip install threading')
os.system('pip install json')
os.system('pip install random')
os.system('pip install getpass')
os.system('pip install random')
os.system('pip install cookielib')
os.system('pip install urllib')
os.system('pip install time')
os.system('pip install colorama')
os.system('pip install hashlib')
os.system('python2 facebook.py')
os.system('cls' if os.name == 'nt' else 'clear') 
print("≠"*60)
print("All offices are now complete")